version: '3'

services:
  mysql:
    image: mysql:latest
    command: >
      --default-authentication-plugin=mysql_native_password
      --innodb-online-alter-log-max-size=1G
    restart: always
    env_file: config.env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  insert_users:
    build: ./scripts
    env_file: config.env
    command: ["node", "insert_users.js"]
    depends_on:
      - mysql

  benchmark:
    build: ./scripts
    env_file: config.env
    command: ["node", "benchmark.js"]
    depends_on:
      - mysql
      - insert_users

volumes:
  mysql_data:
