version: '3'

services:
  mysql:
    image: mysql:8.0.23
    container_name: mysql-container
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test_db
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/mysql
    command: >
      --default-authentication-plugin=mysql_native_password --log-bin=/var/lib/mysql/mysql-bin.log