{
 "title": "Beanstalkd metricss",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Beanstalkd queue size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"beanstalkd_queue_length\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Ops/ sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "alias": "Producer",
     "query": "SELECT non_negative_derivative(mean(\"value\"), 1s) FROM \"beanstalkd_producer_message\" WHERE $timeFilter GROUP BY time(1s) fill(null)"
    },
    {
     "alias": "Consumer",
     "query": "SELECT non_negative_derivative(mean(\"value\"), 1s) FROM \"beanstalkd_consumer_message\" WHERE $timeFilter GROUP BY time(1s) fill(null)"
    }
   ]
  },
  {
   "title": "Consumer ops/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "SELECT non_negative_derivative(mean(\"value\"), 1s) FROM \"beanstalkd_consumer_message\" WHERE $timeFilter GROUP BY time(1s) fill(null)"
    }
   ]
  },
  {
   "title": "Producer ops/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "SELECT non_negative_derivative(mean(\"value\"), 1s) FROM \"beanstalkd_producer_message\" WHERE $timeFilter GROUP BY time(1s) fill(null)"
    }
   ]
  }
 ]
}