version: '3'
services:
  us_server1:
    image: nginx:latest
    volumes:
      - ./servers/nginx.conf:/etc/nginx/nginx.conf
      - ./servers/us_1/index.html:/usr/local/openresty/nginx/html/index.html
      
  us_server2:
    image: nginx:latest
    volumes:
      - ./servers/nginx.conf:/etc/nginx/nginx.conf
      - ./servers/us_2/index.html:/usr/local/openresty/nginx/html/index.html

  uk_server:
    image: nginx:latest
    volumes:
      - ./servers/nginx.conf:/etc/nginx/nginx.conf
      - ./servers/uk/index.html:/usr/local/openresty/nginx/html/index.html

  rest_server:
    image: nginx:latest
    volumes:
      - ./servers/nginx.conf:/etc/nginx/nginx.conf
      - ./servers/rest/index.html:/usr/local/openresty/nginx/html/index.html

  backup_server:
    image: nginx:latest
    volumes:
      - ./servers/nginx.conf:/etc/nginx/nginx.conf
      - ./servers/backup/index.html:/usr/local/openresty/nginx/html/index.html

  load_balancer:
    build: ./load_balancer
    ports:
      - "8080:80"

