filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.modules:
  - module: mysql
    error:
      enabled: true
      var.paths: ["/logs/mysql_error.log*"]
    slowlog:
      enabled: true
      var.paths: ["/logs/mysql-slow.log*"]

output.logstash:
  enabled: true  
  hosts: ["graylog:5050"]  # Point to your Graylog server's Beats input