version: '3.7'

networks:
  private-network:
    driver: bridge

services:
  nginx:
    image: nginx:latest
    networks:
      - private-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
    depends_on:
      - application

  application:
    build: ./application
    networks:
      - private-network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    networks:
      - private-network
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: {}
